recipes = [
   'https://github.com/ahui2016/ffe/raw/main/recipes/anon.py',
   'https://github.com/ahui2016/ffe/raw/main/recipes/common_ibm.py',
   'https://github.com/ahui2016/ffe/raw/main/recipes/ibm-upload.py',
   'https://github.com/ahui2016/ffe/raw/main/recipes/ibm-delete.py',
]
