global_names = [
  '..\dest\',
  '.\aaa\',
  '  ',
]

[global_options]
verbose = true
delete = true
add = false

[[tasks]]
recipe = 'swap'
names = []

[tasks.options]
add = true
delete = false

[[tasks]]
recipe = 'swap'
names = []

[tasks.options]
update = true