
[[tasks]]
recipe = "swap"  # 对调两个文件名（或文件夹名）
names = [        # 文件名（或文件夹名）数量必须是正好两个
  'file1.txt',
  'file2.txt',
]

[tasks.options]
verbose = true  # 显示或不显示程序执行的详细过程

# swap 只能用于不需要移动文件的情况，比如同一个文件夹 (或同一个硬盘分区)
# 内的文件可以操作，而跨硬盘分区的文件则无法处理。

